# Base configs
# baseurl: "https://photography.rampatra.com"
baseurl: "https://mrsaraei.github.io/photography/" 
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Reza"
subtitle: "Linger a little in a Three-second Moment!"
author: "Mohammadreza"
header:
 title: "Linger a little in"
 subtitle: "A 3-second Moment!"
footer:
 name: "Hey, I'm Reza!"
 bio: "I work with photography as an act of three-second attention, drawn to fleeting moments of transition—shifting light, moving bodies, spaces suspended between use and meaning. My practice lives in the tension between observation and interpretation, inviting the viewer to slow down and notice what usually slips past. Step into my world and linger, where three-second moments unfold into visual stories—intimate, deliberate, and quietly alive through the lens."

social_urls:
  twitter: "https://www.twitter.com/rampatra_"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
